# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: UAV-Wiki
site_url: https://phoenixtuav.github.io/uav-wiki
theme:
  name: material
  language: zh
  # logo: assets/logo.png
  # favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
plugins:
- search
markdown_extensions:
  - admonition
# 目录结构可参考 https://github.com/squidfunk/mkdocs-material/blob/047d56bf50c7fac2db39ea868e443d32043f9fda/mkdocs.yml#L183
# 官方教程 https://squidfunk.github.io/mkdocs-material/setup/
nav:
  - 关于本项目: 
    - index.md
    - 如何参与.md
  - 赛事与赛道介绍:
    - 2024年:
      - "赛事与赛道介绍/2024/2024.5 中国机器人大赛暨RoboCup中国赛.md"
      - "赛事与赛道介绍/2024/2024.7 睿抗机器人开发者大赛.md"
      - "赛事与赛道介绍/2024/2024.7 中国机器人及人工智能大赛.md"
      - "赛事与赛道介绍/2024/2024.10 中国机器人大赛暨RoboCup中国赛.md"
    - 2025年:
      - "赛事与赛道介绍/2025/2025.7 睿抗机器人开发者大赛.md"
      - "赛事与赛道介绍/2025/2025.7 中国机器人及人工智能大赛.md"
      # - "赛事与赛道介绍/2025/"
  - 简易开源代码:
    - "简易开源代码/index.md"
    - 仿真环境的部署:
      - "简易开源代码/仿真环境的部署/Ubuntu系统安装.md"
      - "简易开源代码/仿真环境的部署/ROS安装与基础学习.md"
      - "简易开源代码/仿真环境的部署/MAVROS安装.md"
      - "简易开源代码/仿真环境的部署/PX4仿真环境安装.md"
      #- "简易开源代码/仿真环境的部署/激光雷达 MID-360.md"
      - "简易开源代码/仿真环境的部署/深度相机 D435.md"
    - 简易飞行模块使用:
      - "简易开源代码/简易飞行模块使用/编译功能包.md"
      - "简易开源代码/简易飞行模块使用/如何起飞降落.md"
      - "简易开源代码/简易飞行模块使用/定点飞行.md"